@startuml Manage MenuItems
title Manage MenuItems module

actor "Admin" as User
participant "Html Page" as html
participant "Jstree" as jt
participant "AngularJs controller" as js
participant "C# api controller" as api
database "Sql Server" as db


User -> html: want to use Manage MenuItem module

alt Admin clicks on "Add New MenuItem"
    User -> html : go to add MenuItem state
    html -> User : provide MenuItem form
    User -> html : fill MenuItem details(DisplayName , PageUrl , icon , Level , Parent)
    User -> html : click on "add" button
    html -> js : pass data 
    js -> js : validate data
    js -> api : call api method for add MenuItem
    api -> db : call sp for add data
    db -> api : return MenuItem add status
    api -> js : return status of MenuItem add
    html -> User : show MenuItem add status message
    

else Admin clicks on "update MenuItem"
    html -> js: pass Id of requested MenuItem for update
    js -> html: pass data of that MenuItem
    html --> User : show MenuItem update form with old pre-filled data
    User -> html: fill form with updated data and click on update
    html -> js : pass updated data object
    js -> api : validate data and call api method
    api -> db : call sp for update data
    db -> api : return update status message
    api -> js : return update status message
    js --> User : show status message of update

else Admin clicks on "delete MenuItem"
    html -> js: pass Id of requested MenuItem for update
    js -> html: pass data of that MenuItem
    html --> User : show MenuItem Delete alert
    User -> html: click on yes or no
    js -> api : if yes then call api method for delete , otherwise rollback
    api -> db : call sp for delete data
    db -> api : return delete status message
    api -> js : return delete status message
    js --> User : show status message of delete

else Admin clicks on "MenuItem Export to Excel"
    html -> js : call ExportToExcel method
    js -> js : convert MenuItem into alasql myExcel object form
    js -> js : execute alasql command for download excel file

else Admin clicks on "Update Level and DisplayOrder by Drag and Drop"
   js -> api : call method for get MenuItem list
   api -> db : call sp for get MenuItem object
   db -> api : return MenuItems
   api -> js : return MenuItem object as per jstree json object format
   js -> jt : pass json object to jstree instance
   js -> html : create tree structure of MenuItem
   User -> html : update MenuItem Level and DisplayOrder by drag and drop
   User -> html : click on update
   jt -> js : pass updated tree object 
   js -> api : call api method
   api -> db : call sp for update
   db->api : return update status
   api -> js : return update status
   js -> User : show update status

end

@enduml
